export const ROOM_TYPE_STYLE = {
  Standard: "bg-blue-50 text-blue-700 border border-blue-200",
  Premium: "bg-purple-50 text-purple-700 border border-purple-200",
  VIP: "bg-amber-50 text-amber-700 border border-amber-200",
};

export const ROOM_TYPE_INFO = {
  Standard: {
    seatTypes: "Thường, Couple",
    minSeats: 40,
    minRows: 5,
    minCols: 8,
    screen: "Màn chiếu 2K, kích thước tiêu chuẩn.",
    sound: "Âm thanh Dolby 5.1 hoặc 7.1.",
    amenities: "Không yêu cầu tiện ích đặc biệt.",
    desc: "Phòng chiếu tiêu chuẩn — đáp ứng nhu cầu xem phim cơ bản với chất lượng ổn định.",
    seatReq: "Tối thiểu 80% ghế thường, có thể có 1-2 hàng ghế Couple.",
    icon: "🎬",
    border: "border-blue-200",
    bg: "bg-blue-50/60",
    accent: "text-blue-700",
    accentBg: "bg-blue-100",
    badge: "bg-blue-100 text-blue-700 border-blue-200",
  },
  Premium: {
    seatTypes: "Thường, VIP, Đôi",
    minSeats: 60,
    minRows: 6,
    minCols: 10,
    screen: "Màn chiếu 2K/4K, kích thước lớn hơn 20% so với Standard.",
    sound: "Âm thanh Dolby Atmos hoặc DTS:X.",
    amenities: "Có ít nhất 1 tiện ích: bắp nước phục vụ tận ghế, cổng sạc USB.",
    desc: "Phòng chiếu cao cấp — trải nghiệm nâng cao với ghế ngồi rộng hơn, màn hình lớn hơn.",
    seatReq: "Tối đa 2 hàng ghế VIP, >80 ghế: tối đa 3 hàng Couple. ≤80 ghế: tối đa 2 hàng Couple. Còn lại là ghế thường.",
    icon: "✨",
    border: "border-purple-200",
    bg: "bg-purple-50/60",
    accent: "text-purple-700",
    accentBg: "bg-purple-100",
    badge: "bg-purple-100 text-purple-700 border-purple-200",
  },
  VIP: {
    seatTypes: "VIP, Đôi",
    minSeats: 30,
    minRows: 5,
    minCols: 6,
    screen: "Màn chiếu 4K Laser, kích thước lớn nhất.",
    sound: "Âm thanh Dolby Atmos toàn diện.",
    amenities: "Phòng chờ VIP riêng, phục vụ đồ ăn tại ghế, menu premium, chăn/gối miễn phí.",
    desc: "Phòng chiếu hạng sang — không gian riêng tư, dịch vụ đẳng cấp nhất.",
    seatReq: ">80 ghế: tối đa 3 hàng Couple. ≤80 ghế: tối đa 2 hàng Couple. Còn lại là ghế VIP.",
    icon: "👑",
    border: "border-amber-200",
    bg: "bg-amber-50/60",
    accent: "text-amber-700",
    accentBg: "bg-amber-100",
    badge: "bg-amber-100 text-amber-700 border-amber-200",
  },
};
